//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public CV()
        {
            this.CV_EGITIM = new HashSet<CV_EGITIM>();
            this.CV_KARIYER = new HashSet<CV_KARIYER>();
            this.CV_NITELIK = new HashSet<CV_NITELIK>();
            this.CV_REFERANS = new HashSet<CV_REFERANS>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid KULLANICI_ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string AD_SOYAD { get; set; }
        public string E_POSTA { get; set; }
        public string DIGER_EPOSTA { get; set; }
        public string TC_KIMLIK { get; set; }
        public System.DateTime DOGUM_TARIH { get; set; }
        public string FOTOGRAF { get; set; }
        public string UYRUK { get; set; }
        public byte CINSIYET { get; set; }
        public Nullable<System.Guid> ULKE { get; set; }
        public Nullable<System.Guid> SEHIR { get; set; }
        public string ADRES { get; set; }
        public string CEP_TEL { get; set; }
        public string DIGER_CEP { get; set; }
        public string EV_TEL { get; set; }
        public string IS_TEL { get; set; }
        public string DAHILI { get; set; }
        public string DOGUM_YER { get; set; }
        public byte MEDENI_DURUM { get; set; }
        public Nullable<byte> ASKERLIK_DURUM { get; set; }
        public Nullable<System.DateTime> TERHIS_TARIH { get; set; }
        public string UYE_TOPLULUKLAR { get; set; }
        public Nullable<bool> SIGARA { get; set; }
        public string SEYEHAT_DURUM { get; set; }
        public string EHLIYET { get; set; }
        public string HOBILER { get; set; }
        public string FACEBOOK { get; set; }
        public string LINKEDIN { get; set; }
        public string TWITTER { get; set; }
        public string GOOGLEPLUS { get; set; }
        public string DEGISTIREN { get; set; }
        public Nullable<System.DateTime> DEGISTIRME_TARIH { get; set; }
        public string OLUSTURAN { get; set; }
        public System.DateTime OLUSTURMA_TARIH { get; set; }
        public bool SILINDI { get; set; }
        public string CV_BASLIK { get; set; }
        public string MESLEK { get; set; }
        public Nullable<byte> IS_DURUM { get; set; }
    
        public virtual ICollection<CV_EGITIM> CV_EGITIM { get; set; }
        public virtual ICollection<CV_KARIYER> CV_KARIYER { get; set; }
        public virtual ICollection<CV_NITELIK> CV_NITELIK { get; set; }
        public virtual ICollection<CV_REFERANS> CV_REFERANS { get; set; }
        public virtual KULLANICI KULLANICI { get; set; }
    }
}
