//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_EGITIM
    {
        public System.Guid ID { get; set; }
        public System.Guid CV_ID { get; set; }
        public byte EGITIM_DURUM { get; set; }
        public byte EGITIM_DURUM_TIP { get; set; }
        public string OKUL { get; set; }
        public string BOLUM { get; set; }
        public string OGRETIM_DIL { get; set; }
        public Nullable<byte> EGITIM_TIP { get; set; }
        public string ULKE_AD { get; set; }
        public System.DateTime BASLANGIC_TARIH { get; set; }
        public Nullable<System.DateTime> BITIS_TARIH { get; set; }
        public Nullable<bool> YAN_ANADAL { get; set; }
        public Nullable<bool> CIFT_ANADAL { get; set; }
        public string DIGER_BOLUM { get; set; }
    
        public virtual CV CV { get; set; }
    }
}
