//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_KARIYER
    {
        public System.Guid ID { get; set; }
        public System.Guid CV_ID { get; set; }
        public string FIRMA { get; set; }
        public string POZISYON { get; set; }
        public string FIRMA_YER { get; set; }
        public string SEKTOR { get; set; }
        public byte CALISMA_TIP { get; set; }
        public byte CALISMA_DURUM { get; set; }
        public System.DateTime BASLANGIC { get; set; }
        public Nullable<System.DateTime> BITIS { get; set; }
        public string AYRILMA_NEDEN { get; set; }
        public string DENEYIM { get; set; }
    
        public virtual CV CV { get; set; }
    }
}
