//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_NITELIK
    {
        public System.Guid ID { get; set; }
        public System.Guid CV_ID { get; set; }
        public string NITELIK { get; set; }
        public string SEVIYE { get; set; }
        public string YIL { get; set; }
        public string ACIKLAMA { get; set; }
    
        public virtual CV CV { get; set; }
    }
}
