//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_REFERANS
    {
        public System.Guid ID { get; set; }
        public System.Guid CV_ID { get; set; }
        public byte REFERANS_TIP { get; set; }
        public string AD_SOYAD { get; set; }
        public string FIRMA { get; set; }
        public string POZISYON { get; set; }
        public string TEL { get; set; }
        public string E_POSTA { get; set; }
    
        public virtual CV CV { get; set; }
    }
}
