//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMA
    {
        public FIRMA()
        {
            this.KULLANICI = new HashSet<KULLANICI>();
        }
    
        public System.Guid ID { get; set; }
        public string FIRMA_AD { get; set; }
        public string TELEFON_1 { get; set; }
        public string TELEFON_2 { get; set; }
        public string E_POSTA { get; set; }
        public string DIGER_E_POSTA { get; set; }
        public Nullable<System.DateTime> DEGISTIRILME_TARIH { get; set; }
        public string DEGISTIREN { get; set; }
        public System.DateTime OLUSTURULMA_TARIH { get; set; }
        public string OLUSTURAN { get; set; }
        public Nullable<bool> SILINDI { get; set; }
    
        public virtual ICollection<KULLANICI> KULLANICI { get; set; }
    }
}
