//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kariyer.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KariyerEntities : DbContext
    {
        public KariyerEntities()
            : base("name=KariyerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CV> CV { get; set; }
        public virtual DbSet<CV_EGITIM> CV_EGITIM { get; set; }
        public virtual DbSet<CV_KARIYER> CV_KARIYER { get; set; }
        public virtual DbSet<CV_NITELIK> CV_NITELIK { get; set; }
        public virtual DbSet<CV_REFERANS> CV_REFERANS { get; set; }
        public virtual DbSet<FIRMA> FIRMA { get; set; }
        public virtual DbSet<KULLANICI> KULLANICI { get; set; }
    }
}
